repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: bash -c "cd Python-formatter && flake8"
        language: python
        pass_filenames: false
        files: ^Python-formatter/
        types: [ python ]
